# Generated by Django 2.0.2 on 2018-02-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='player',
            new_name='character',
        ),
        migrations.AddField(
            model_name='transaction',
            name='error_message',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('D', 'Deposit'), ('W', 'Withdraw')], max_length=1),
        ),
    ]
