# Generated by Django 2.0.2 on 2018-06-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20180213_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionfile',
            name='file',
            field=models.FileField(unique=True, upload_to=''),
        ),
    ]
