# Generated by Django 2.0.2 on 2018-11-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20180619_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionfile',
            options={'verbose_name': 'file', 'verbose_name_plural': 'files'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('move', 'Move'), ('repair', 'Repair')], max_length=10),
        ),
    ]
