# Generated by Django 2.0.2 on 2018-12-07 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_player_active'),
        ('sales', '0002_saletransaction_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='characters',
        ),
        migrations.RemoveField(
            model_name='saletransaction',
            name='character',
        ),
        migrations.AddField(
            model_name='sale',
            name='players',
            field=models.ManyToManyField(null=True, related_name='sale_players', to='player.Player'),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='player.Player'),
        ),
    ]
