# Generated by Django 2.0.2 on 2018-02-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='expansion',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemId',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='points',
            field=models.IntegerField(null=True),
        ),
    ]
