# Generated by Django 2.0.2 on 2018-06-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20180212_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
