# Generated by Django 2.0.2 on 2018-06-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_itemname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AlterField(
            model_name='item',
            name='itemId',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
